### ISSUE TITLE
SPI I2SCLKP register typo

### ISSUE THREAD

**Issue by kossnikita** [ArteryTek/PACKs#2]
All reference manuals have register I2SCLKP. But only in AT32F423 SVD is it named correctly. In all others it is called I2SCLK.
![image](https://github.com/ArteryTek/PACKs/assets/39294101/8d9ff56c-7f86-4798-8616-5258e89c44e9)

**Comment by ArteryTek** [comment]
Thanks for your reply, fixed in next version.
