### ISSUE TITLE
ACC CTRL2 field typo

### ISSUE THREAD

**Issue by kossnikita** [ArteryTek/PACKs#3]
In AT32F415 reference Rev 2.03 there is no ACC periphery, but it is in the SVD.

In AT32F415, AT32WB415 and AT32F425 SVDs:

- Unnecessary "ACC_" prefix in field
- `HSI` instead `HICK`
- `TRIM` instead `TWK` (in reference manuals too!)

What does `TWK` mean, by the way? In almost all manuals it is called `HICKTRIM`.

![image](https://github.com/ArteryTek/PACKs/assets/39294101/949895a2-19f3-4631-8cd0-089806a5701d)

**Comment by ArteryTek** [comment]
Thanks for your reply, fixed in next version.
